<div class="appui-server-domain bbn-overlay">
  <bbn-router :scrollable="true"
              :autoload="true"
              ref="router"
              :nav="true">
    <bbns-container url="home"
                    :static="true"
                    :load="false"
                    :source="source"
                    icon="nf nf-fa-home"
                    bcolor="turquoise"
                    fcolor="white"
                    title="<?=_("Home")?>"
                    component="appui-server-domain-dashboard"
                    :notext="true"/>
    <bbns-container url="subdomains"
                    :load="false"
                    :static="true"
                    component="appui-server-domain-subdomains"
                    icon="nf nf-fa-th_list"
                    bcolor="darkkhaki"
                    fcolor="white"
                    :source="source"
                    title="<?=_("Sub-domains")?>"
                    :notext="true"/>
    <bbns-container url="users"
                    :load="false"
                    :static="true"
                    component="appui-server-domain-users"
                    icon="nf nf-fa-users"
                    bcolor="darkseagreen"
                    fcolor="white"
                    :source="source"
                    title="<?=_("Users")?>"
                    :notext="true"/>
    <bbns-container url="information"
                    :load="false"
                    :static="true"
                    component="appui-server-domain-information"
                    icon="nf nf-fa-info"
                    bcolor="steelblue"
                    fcolor="white"
                    :source="source"
                    title="<?=_("Information")?>"
                    :notext="true"/>
    <bbns-container url="commands"
                    :load="false"
                    :static="true"
                    component="appui-server-domain-commands"
                    icon="nf nf-mdi-function"
                    bcolor="firebrick"
                    fcolor="white"
                    :source="source"
                    title="<?=_("Commands")?>"
                    :notext="true"/>
  </bbn-router>
</div>
